language: node_js
node_js:
  - "8.11.1"
deploy:
  provider:
    - firebase
cache:
  directories:
    - "node_modules"
before_install:
  - npm i -g npm
  - npm install -g @vue/cli
script:
  - npm install
  - npm run build
install:
  - npm install -g firebase-tools
after_success:
  - firebase deploy --token $FIREBASE_TOKEN
